# Generated by Django 3.1.14 on 2022-05-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_merge_20220517_1128'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='annotation',
            name='task_comple_last_ac_777e69_idx',
        ),
        migrations.RemoveIndex(
            model_name='annotation',
            name='task_comple_last_cr_dedad7_idx',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='last_action',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='last_created_by',
        ),
    ]
